clear all; close all; clc;
% Plot the static force map of a festo muscle actuator
% Data must be generated by the test stand of M. Drummond (TU Berlin)
% Author: Mirco Martens (TU Berlin)
% Date: 02.11.2016

%% Get data from file
filename = 'data2.txt';
data = readDataFile_StaticForceMap(filename);

%% Prepare data for 3d-plot
numberMeasurementsPerLength = sum(data(:,1)==data(2,1));
musclePressure = data(1,2:end);
muscleLength = flipud(unique(data(2:end,1)));
data = data(2:end,2:end);
muscleForce = zeros(length(muscleLength),length(musclePressure));
rowNumber = 1;
for i=1:length(muscleLength)
   midValVec = zeros(1,length(musclePressure));
   for j=1:numberMeasurementsPerLength
       midValVec = midValVec + data(rowNumber,:);
       rowNumber = rowNumber + 1;
   end
   muscleForce(i,:) = (midValVec / numberMeasurementsPerLength);
end

%% 3d plot
f = figure;
set(f,'Units', 'normalized', 'Position', [0.1, 0.1, 0.5, 0.7]); 
surf(musclePressure,muscleLength,muscleForce);
xlabel('Pessure [bar]');
ylabel('Length [m]');
zlabel('Force [N]');